---
version: 2
updates:
  - package-ecosystem: bundler
    directory: "/backend/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - "otherguy"
    reviewers:
      - "otherguy"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - "otherguy"
    reviewers:
      - "otherguy"
  - package-ecosystem: pub
    directory: "/mobile/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - "otherguy"
    reviewers:
      - "otherguy"
