source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.4.6"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 7.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use sqlite3 and PostgreSQL as the databases for Active Record
gem "pg", "~> 1.6"
gem "sqlite3", "~> 2.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", "~> 1.18", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"

# Strong Migrations
# Read more: https://github.com/ankane/strong_migrations
gem "strong_migrations", "~> 2.0"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors", "~> 3.0"

# Use Active Model has_secure_password for authentication
gem "bcrypt", "~> 3.1"

# JSON Web Token library
gem "jwt", "~> 3.1"

# UUID v7 generation
gem "uuid7", "~> 0.2"

# Sanitize html from inputs
gem "sanitize", "~> 7.0"

group :development, :test do
  # Load environment variables from .env files [https://github.com/bkeepers/dotenv]
  gem "dotenv-rails", "~> 3.1"

  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", "~> 1.11", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", "~> 7.1", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", "~> 1.1", require: false
  gem "rubocop-rspec", "~> 3.7", require: false
  gem "rubocop-factory_bot", "~> 2.26", require: false

  # RSpec testing framework
  gem "rspec-rails", "~> 8.0"

  # RSpec Formatters
  gem "rspec_junit_formatter", "~> 0.6", require: false
  gem "rspec-sonarqube-formatter", "~> 1.5", require: false

  # Swagger/OpenAPI documentation
  gem "rswag-specs", "~> 2.16"

  # Use Factory Bot for fixtures
  gem "factory_bot_rails", "~> 6.5"

  # Use Faker for generating fake data
  gem "faker", "~> 3.5"

  # Use Shoulda Matchers for concise tests
  gem "shoulda-matchers", "~> 6.2"

  # Code coverage analysis
  gem "simplecov", "~> 0.22", require: false
  gem "simplecov-console", "~> 0.9", require: false
  gem "simplecov_json_formatter", "~> 0.1", require: false

  # Gem version constraint management tool [https://github.com/joonty/pessimize]
  gem "pessimize", "~> 0.5"
end
