source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 7.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use sqlite3 and PostgreSQL as the databases for Active Record
gem "pg", "~> 1.6"
gem "sqlite3", "~> 2.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", "~> 1.18", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors", "~> 3.0"

# Use Active Model has_secure_password for authentication
gem "bcrypt", "~> 3.1"

# JSON Web Token library
gem "jwt", "~> 3.1"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", "~> 1.11", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", "~> 7.1", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", "~> 1.1", require: false
  gem "rubocop-rspec", "~> 3.7", require: false

  # RSpec testing framework
  gem "rspec-rails", "~> 7.1"

  # Swagger/OpenAPI documentation
  gem "rswag-specs", "~> 2.16"

  gem "drg", "~> 1.6"
  gem "abbrev", "~> 0.1"
  gem "byebug", "~> 12.0"
end
